# aah framework - Docker Release build file

FROM golang:latest
LABEL maintainer="Jeevanandam M. <jeeva@myjeeva.com>"

RUN go version

RUN apt-get update

RUN rm -rf $GOPATH/src

RUN go get -u aahframework.org/tools.v0/aah && \
    go get -u github.com/aah-cb/minify && \
    go get -u github.com/aah-cb/ve-pug

RUN aah --version

WORKDIR $GOPATH/src
